### ISSUE TITLE
`characterizethis` is missing from the dependencies

### ISSUE THREAD

**Issue by barentsen** [christinahedges/wellfit#7]
The module `wellfit/wellfit.py` imports `characterizethis`, however this is not listed as a dependency in `setup.py`.  As a result, `wellfit` crashed when I tried to import it for the first time.

**Comment by christinahedges** [comment]
This is a really good point. I think the best solution to this issue is to actually rip the useful part out of `characterizethis` and put it in the `wellfit` utils. I think that will end up being easier to maintain, because `ct` is never going to be that stable... For now, I've added it as a dependency. Thanks for bringing this up!
